"use client";
import React, { useEffect } from "react";
import Searchbar from "@/app/components/Searchbar";
import FlightTable from "./FlightTable";
import flightInterface from "@/app/interfaces/flight";
export default function FlightSelectionControl() {
  const currentDate = new Date();
  const flight: flightInterface = {
    originCode: "LAX",
    originLocation: "Los Angeles, USA",
    destinationCode: "NRT",
    destinationLocation: "Tokyo, Japan",
    flightNumber: "480",
    departureTime: new Date(currentDate.getTime() + 7 * 24 * 60 * 60 * 1000),
    arrivalTime: new Date(currentDate.getTime() + 14 * 24 * 60 * 60 * 1000),
    currentDate: new Date(),
    price: 420,
    duration: "2h",
    seatsBusinessClass: [
      "available",
      "",
      "available",
      "available",
      "",
      "",
      "available",
      "",
      "available",
      "",
      "",
      "available",
    ],
    seatsComfort: [
      "available",
      "",
      "available",
      "available",
      "",
      "",
      "available",
      "",
      "available",
      "",
      "",
      "available",
      "available",
      "",
      "available",
      "available",
      "",
      "",
      "available",
      "",
      "available",
      "",
      "",
      "available",
      "available",
      "",
      "available",
      "available",
      "",
      "",
      "available",
      "",
      "available",
      "",
      "",
      "available",
    ],
    seatsOrdinary: [
      "available",
      "",
      "available",
      "",
      "",
      "available",
      "available",
      "",
      "",
      "",
      "available",
      "",
      "available",
      "",
      "available",
      "",
      "",
      "available",
      "",
      "",
      "available",
      "",
      "",
      "available",
      "available",
      "available",
      "",
      "available",
      "",
      "",
      "",
      "available",
      "available",
      "",
      "",
      "available",
      "available",
      "",
      "available",
      "",
      "",
      "available",
      "available",
      "",
      "",
      "",
      "available",
      "",
      "available",
      "",
      "available",
      "",
      "",
      "available",
      "",
      "",
      "available",
      "",
      "",
      "available",
      "available",
      "available",
      "",
      "available",
      "",
      "",
      "",
      "available",
      "available",
      "",
      "",
      "available",
      "available",
      "",
      "available",
      "",
      "",
      "available",
      "available",
      "",
      "",
      "",
      "available",
      "",
      "available",
      "",
      "available",
      "",
      "",
      "available",
      "",
      "",
      "available",
      "",
      "",
      "available",
      "available",
      "available",
      "",
      "available",
      "",
      "",
      "",
      "available",
      "available",
      "",
      "",
      "available",
    ],
  };
  const flight2: flightInterface = {
    originCode: "USA",
    originLocation: "Los Angeles, USA",
    destinationCode: "UKS",
    destinationLocation: "Tokyo, Japan",
    flightNumber: "480",
    departureTime: new Date(currentDate.getTime() + 7 * 24 * 60 * 60 * 1000),
    arrivalTime: new Date(currentDate.getTime() + 14 * 24 * 60 * 60 * 1000),
    currentDate: new Date(),
    price: 420,
    duration: "2h",
    seatsBusinessClass: [
      "available",
      "",
      "available",
      "available",
      "",
      "",
      "available",
      "",
      "available",
      "",
      "",
      "available",
    ],
    seatsComfort: [
      "available",
      "",
      "available",
      "available",
      "",
      "",
      "available",
      "",
      "available",
      "",
      "",
      "available",
      "available",
      "",
      "available",
      "available",
      "",
      "",
      "available",
      "",
      "available",
      "",
      "",
      "available",
      "available",
      "",
      "available",
      "available",
      "",
      "",
      "available",
      "",
      "available",
      "",
      "",
      "available",
    ],
    seatsOrdinary: [
      "available",
      "",
      "available",
      "",
      "",
      "available",
      "available",
      "",
      "",
      "",
      "available",
      "",
      "available",
      "",
      "available",
      "",
      "",
      "available",
      "",
      "",
      "available",
      "",
      "",
      "available",
      "available",
      "available",
      "",
      "available",
      "",
      "",
      "",
      "available",
      "available",
      "",
      "",
      "available",
      "available",
      "",
      "available",
      "",
      "",
      "available",
      "available",
      "",
      "",
      "",
      "available",
      "",
      "available",
      "",
      "available",
      "",
      "",
      "available",
      "",
      "",
      "available",
      "",
      "",
      "available",
      "available",
      "available",
      "",
      "available",
      "",
      "",
      "",
      "available",
      "available",
      "",
      "",
      "available",
      "available",
      "",
      "available",
      "",
      "",
      "available",
      "available",
      "",
      "",
      "",
      "available",
      "",
      "available",
      "",
      "available",
      "",
      "",
      "available",
      "",
      "",
      "available",
      "",
      "",
      "available",
      "available",
      "available",
      "",
      "available",
      "",
      "",
      "",
      "available",
      "available",
      "",
      "",
      "available",
    ],
  };
  const [flights, setFlights] = React.useState([flight, flight2]);

  return (
    <div>
      <Searchbar></Searchbar>
      <div className="">
        <h2>Choose a flight</h2>
        <ul>
          <li>Flight 1</li>
          <li>Flight 2</li>
          <li>Flight 3</li>
        </ul>
        <FlightTable flights={flights}></FlightTable>
      </div>
    </div>
  );
}
